--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3 (Debian 16.3-1.pgdg120+1)
-- Dumped by pg_dump version 16.3 (Debian 16.3-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_holders; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.account_holders (
    account_holder_id bigint NOT NULL,
    account_holder_address character varying(255),
    account_holder_email character varying(255),
    account_holder_name character varying(255),
    account_holder_phone_number character varying(255),
    account_holder_surname character varying(255),
    creation_time timestamp(6) without time zone,
    account_holder_identity_number character varying(255)
);


ALTER TABLE public.account_holders OWNER TO root;

--
-- Name: account_holders_account_holder_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.account_holders ALTER COLUMN account_holder_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_holders_account_holder_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.accounts (
    account_id bigint NOT NULL,
    account_balance bigint,
    account_name character varying(255),
    account_number character varying(255),
    creation_time timestamp(6) without time zone,
    version bigint,
    holder_id bigint NOT NULL,
    bank_id bigint NOT NULL
);


ALTER TABLE public.accounts OWNER TO root;

--
-- Name: accounts_account_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.accounts ALTER COLUMN account_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: banks; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.banks (
    bank_id bigint NOT NULL,
    bank_address character varying(255),
    bank_code character varying(255),
    bank_creation_time timestamp(6) without time zone,
    bank_name character varying(255),
    bank_phone_number character varying(255)
);


ALTER TABLE public.banks OWNER TO root;

--
-- Name: banks_bank_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.banks ALTER COLUMN bank_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.banks_bank_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.transactions (
    transaction_id bigint NOT NULL,
    transaction_amount bigint,
    transaction_code character varying(255),
    transaction_description character varying(255),
    transaction_status character varying(255),
    transaction_time timestamp(6) without time zone,
    transaction_type character varying(255),
    account_id bigint NOT NULL
);


ALTER TABLE public.transactions OWNER TO root;

--
-- Name: transactions_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.transactions ALTER COLUMN transaction_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: account_holders; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.account_holders (account_holder_id, account_holder_address, account_holder_email, account_holder_name, account_holder_phone_number, account_holder_surname, creation_time, account_holder_identity_number) FROM stdin;
\.


--
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.accounts (account_id, account_balance, account_name, account_number, creation_time, version, holder_id, bank_id) FROM stdin;
\.


--
-- Data for Name: banks; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.banks (bank_id, bank_address, bank_code, bank_creation_time, bank_name, bank_phone_number) FROM stdin;
\.


--
-- Data for Name: transactions; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.transactions (transaction_id, transaction_amount, transaction_code, transaction_description, transaction_status, transaction_time, transaction_type, account_id) FROM stdin;
\.


--
-- Name: account_holders_account_holder_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.account_holders_account_holder_id_seq', 1, false);


--
-- Name: accounts_account_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.accounts_account_id_seq', 1, false);


--
-- Name: banks_bank_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.banks_bank_id_seq', 1, false);


--
-- Name: transactions_transaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.transactions_transaction_id_seq', 1, false);


--
-- Name: account_holders account_holders_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.account_holders
    ADD CONSTRAINT account_holders_pkey PRIMARY KEY (account_holder_id);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (account_id);


--
-- Name: banks banks_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.banks
    ADD CONSTRAINT banks_pkey PRIMARY KEY (bank_id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (transaction_id);


--
-- Name: transactions fk20w7wsg13u9srbq3bd7chfxdh; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fk20w7wsg13u9srbq3bd7chfxdh FOREIGN KEY (account_id) REFERENCES public.accounts(account_id);


--
-- Name: accounts fkb78evw9x9jyy66ld572kl8rgx; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT fkb78evw9x9jyy66ld572kl8rgx FOREIGN KEY (bank_id) REFERENCES public.banks(bank_id);


--
-- Name: accounts fkj0l567ummxwudo4igft3j58vr; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT fkj0l567ummxwudo4igft3j58vr FOREIGN KEY (holder_id) REFERENCES public.account_holders(account_holder_id);


--
-- PostgreSQL database dump complete
--

