global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'sekom_prometheus'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'app-sekom:8082'
          - 'app:8082'
