global:
  scrape_interval: 5s # Metriklerin her 5 saniyede bir toplanması

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'spring-boot-app'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:8082' ] # Spring Boot uygulamanızın adresi

