version: '3.8'
services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: sekom-bank
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
    networks:
      - monitoring

  redis:
    image: redis:latest
    container_name: redis_sekom
    ports:
      - 6379:6379
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_sekom
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
